language: ruby

cache:
  bundler: true
  directories:
    - vendor/bundle

rvm:
  - 2.3.3
  - 2.2.6
  - 2.1.9
  - ruby-2.0.0-p648


before_install:
  - gem update --system
  - gem update bundler
  - gem --version

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: "bundle exec rake test"

services:
  - memcached

gemfile:
  - Gemfile
  - gemfiles/libraries.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails32.gemfile

matrix:
  exclude:
    # Rails 5.0+ requires Ruby 2.2.2 or higher
    - rvm: 2.1.9
      gemfile: gemfiles/rails50.gemfile
    - rvm: ruby-2.0.0-p648
      gemfile: gemfiles/rails50.gemfile
    - rvm: ruby-2.0.0-p648
      gemfile: gemfiles/rails42.gemfile
    - rvm: ruby-2.0.0-p648
      gemfile: gemfiles/rails32.gemfile

notifications:
  slack:
    rooms:
      secure: Ae9tJmBO9/sgYWthHRS5uufAf8s6uIMdtmQn+gBkcAXaMWJgt1IAzpIj98Qsg15/lhHS8ezwCe7WIAWC4mM1cnwl/hP195dbgLzF4D2uOjaIXj55ckIIE06jBX1yHapu0vMFSaKwgL4auEEVg4xkehBb9TzLNG/LbExadZQOIkeLdtgU04VrPfDC9pZWPplXT4kzjMZkMESzBYaCfNl6eenu0sHdoxSvngv52MImog6aZQKT+k3ccAa1yzZNhUdy4gSZi1HafXdSCn4UTPDtkNIlsWBW8yprICLxZV/NvgUTEEJYSHO6Ucx9Er22LzKtNbEYlAs1GErGWjDzpqvvXt/5UwNx0rLDrVKI/xMIELEbT047mSgJ8tpVd0ErGA/bnDfbF2oDFTAEXq4jaeAMaVR9Q1CW0ZZF2Jh5jOKc41U+AVGgaMDaBA0ukDSeXvJcnteZ9EllOO8ZAtC2FKtBNnj36W13KTR0TkjMCl+KOiVJXnOyRJIR+CUL9BdDuODBVPZHqZaZ48N+MOG9dRb+fvkdTnwh7hU+UmR08kOsd4x+dDlm4dBrFrB8v8udQ7XuBN9AOZty2CPWFUSJM1BxtetyS3We0L6lQ8o/B9STFNK4KTa/M8wNq1Fm85h3ZKHHIHDpQnXM6vD8SV1p9u91C5UI8rEyxzW5IaT2oqXsCzU=
